import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ConvexClientProvider } from "./ConvexClientProvider";
import {ClerkProvider} from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import Navbar from "@/components/utility/navbar";

import { Toaster } from "sonner";



const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vivid Platform",
  description: "Generated by Vivid Platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>

       <body
        className={`${inter.className} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClerkProvider
            appearance={{
        theme: dark,
      }}>
              <ConvexClientProvider>
             
                <Navbar/>
                <Toaster  richColors/>
                
                <main className=" bg-white dark:bg-black min-h-screen text-gray-800 dark:text-White overflow-x-hidden">
                  {children}
                </main>
              </ConvexClientProvider>
            </ClerkProvider>
          </ThemeProvider>
        </body>
     
    </html>
  );
}
